get http://localhost:3000/api/merch
###
post http://localhost:3000/api/merch/create
Content-Type: application/json
Authorization: Bearer jekibahumu

{
    "title":"Jeki",
    "link":"none",
    "image":"none",
    "price":15000,
    "categoryId":1
}

###
get http://localhost:3000/api/banner

###
get http://localhost:3000/api/event